{{- if and .Values.dapr.enabled .Values.dapr.cronBindings }}
{{- range $name, $config := .Values.dapr.cronBindings }}
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ $name }}-cron
  namespace: {{ $.Values.namespace }}
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: {{ $config.schedule | quote }}
    - name: direction
      value: "input"
{{- end }}
{{- end }}
