apiVersion: v2
name: {{APP_NAME}}
description: Helm chart for deploying {{APP_NAME}} to Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"

# Maintainer information (optional)
maintainers:
  - name: Your Name
    email: your.email@example.com

# Keywords for chart search (optional)
keywords:
  - {{APP_NAME}}
  - kubernetes
  - microservices

# Home page URL (optional)
# home: https://github.com/your-org/{{APP_NAME}}

# Source code repository (optional)
# sources:
#   - https://github.com/your-org/{{APP_NAME}}
